### Recuperar todas las peliculas
GET http://localhost:3000/movies
### Recuperar una pelicula por ID
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
### Recuperar peliculas por Año
GET http://localhost:3000/movies?year=2000
### Recuperar peliculas por Genero
GET http://localhost:3000/movies?genre=sci-fi
### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json
{
    "title": "El sicario",
    "year": 2026,
    "director": "Frank Redolfo",
    "duration": 163,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Drama",
        "Adventure",
        "Sci-Fi"
    ],
    "rate": 9.98
}
### Actualizar una pelicula
PATCH http://localhost:3000/movies/7d2832f8-c70a-410e-8963-4c93bf36cc9c
Content-Type: application/json
{
    "year": 1900
}
### Eliminar una pelicula
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las series
GET http://localhost:3000/series
### Recuperar serie por ID
GET http://localhost:3000/series/s08-3j4k-5l6m-7n8o-654pq321rs88
### Recuperar serie por cant TEMPORADAS
GET http://localhost:3000/series?season=2
### Recuperar serie por GENRE
GET http://localhost:3000/series?genre=crime

### Recuperar todos los juegos
GET http://localhost:3000/games
### Recuperar juego por ID
GET http://localhost:3000/games/5e82b624-0b7c-421f-9af8-2ec4b2b17e22
### Recuperar los juegos por plataforma
GET http://localhost:3000/games?platform=pc