### Recuperar todas las PELICULAS
GET http://localhost:3000/movies
### Recuperar una pelicula por ID
GET http://localhost:3000/movies/68895e42f3975a4ba7c0ea71
### Recuperar peliculas por Año
GET http://localhost:3000/movies?year=2000
### Recuperar peliculas por Genero
GET http://localhost:3000/movies?genre=sci-fi
### Crear una pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Nueva movie",
    "year": 2026,
    "director": "Frank Redolfo",
    "duration": 163,
    "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre": [
        "Drama",
        "Adventure",
        "Sci-Fi"
    ],
    "rate": 9.98,
    "trailerUrl": "https://www.youtube.com/watch?v=5QqkTUFdnE8"
}
### Actualizar una pelicula
PATCH http://localhost:3000/movies/7d2832f8-c70a-410e-8963-4c93bf36cc9c
Content-Type: application/json

{
    "year": 2000   
}
### Eliminar una pelicula
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### Recuperar todas las SERIES
GET http://localhost:3000/series
### Recuperar serie por ID
GET http://localhost:3000/series/68e33531343f0dbb9b0c318a
### Recuperar serie por cant TEMPORADAS
GET http://localhost:3000/series?season=2
### Recuperar serie por GENRE
GET http://localhost:3000/series?genre=crime
### Actualizar una SERIE
PATCH http://localhost:3000/series/s02-7c6d-8e9f-0g1h-234ij567kl22
Content-Type: application/json

{
    "year": 2025
}

### Recuperar todos los JUEGOS
GET http://localhost:3000/games
### Recuperar juego por ID
GET http://localhost:3000/games/5e82b624-0b7c-421f-9af8-2ec4b2b17e22
### Recuperar los juegos por plataforma
GET http://localhost:3000/games?platform=pc

### Recuperar todos los USUARIOS
GET http://localhost:3000/users
### Recuperar un USUARIO por ID
GET http://localhost:3000/users/68e7511e70ee9147ac2b4bdc
### Crear un USUARIO
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Federico",
    "lastName": "Redolfo",
    "email": "fdera@gmail.com",
    "password": "Federico"
}